volumes:
  aws_db: 

services:
  frontend: 
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks: 
      - aws-network
    volumes: 
      - ./frontend:/frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks: 
      - aws-network
    volumes: 
      - ./backend/:/backend
  mysql:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    container_name: mysql
    ports:
      - 3307:3306
    volumes: 
      - aws_db:/var/lib/mysql
    networks: 
      - aws-network
networks:
  aws-network:
    driver: bridge